### ISSUE TITLE
Get detected randomly and instantly with no ai detection

### ISSUE THREAD

**Issue by FalcoGer** [GABRlEL/payday2.pw-Mods#1] opened 2021-08-24 01:06 UTC
Sometimes, seemingly at random, cameras and AI detect me, corpses or bags. The `?` doesn't show, it instantly goes to `!`.

**Comment by GABRlEL** [comment] 2022-03-26 16:26
Hey, I updated and improved the mod. Please check if the issue is still there.

**Comment by GABRlEL** [comment] 2022-04-05 09:40
Will close the issue as I tested the mod myself. Feel free to contact me again, if you need more help.

**Closed by GABRlEL** 2022-04-05 09:40 UTC
